# Generated by Django 4.0.1 on 2022-03-10 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0004_alter_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
