# Generated by Django 4.0.1 on 2022-03-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0005_remove_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default=True, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
